### PR TITLE
Feature tests

### PR DESCRIPTION
**Pull request by Timmotus**
Added a bunch of tests, not yet for everything though.

### CODE REVIEW

**Review by jasperdewinther — COMMENTED** [review]
jasper@jasper-desktop:~/Documents/r2d2-python-build$ python3 modules/swarm_ui/module/tests/test_main.py 
Traceback (most recent call last):
  File "modules/swarm_ui/module/tests/test_main.py", line 4, in <module>
    import module.frame_functions as frame_functions
ModuleNotFoundError: No module named 'module'

It does work normally when running from inside the swarm_ui directory.

**Comment by Timmotus** [comment]
You can run a test with pytest using `python -m pytest <file>`, you need to pip install pytest first though.

**Comment by jasperdewinther** [comment]
test_add_command_from_json does not pass the test on my pc

**Comment by Timmotus** [comment]
that is correct, the function add_command_from_json does not work right and needs a fix on another branch. The test is correct though.

**Review by jasperdewinther — APPROVED** [review]

**Pull request merged**
